### ISSUE TITLE
Cron issues

### ISSUE THREAD

**Issue by berniemoran** [kiwiz/411-docker#2]
The installed crontab does not appear to work. Install rsyslog shows incorrect permissions on 411_cron.
Correcting with chmod 600 /etc/cron.d/411_cron allows the job to run, but although the job runs, when output to a log file, the job still does not run via cron. Works fine manually.
The web interface continues to show the message 'processor has not run for 20 minutes'.

**Comment by kiwiz** [comment]
Thanks for the report! In fixing this issue, I realized that sending mail is also broken. :/ Looking into fixes (it seems to be relating to https://github.com/docker-library/php/issues/135).

**Comment by kiwiz** [comment]
Fixed for real.
