### ISSUE TITLE
Where to set Elasticsearch IP address and I get below error

### ISSUE THREAD

**Issue by sathishdsgithub** [kiwiz/411-docker#4]
I'm unable to execute `docker-compose up` and I don't know how to query the logs from elasticsearch . Please assist me. I get below error message on the 411 console.

`Error: Uncaught TypeError: Cannot use 'in' operator to search for 'success' in <br /> <b>Fatal error</b>: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51 Stack trace: #0 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(71): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool-&gt;nextConnection() #1 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(89): Elasticsearch\Transport-&gt;getConnection() #2 /var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(229): Elasticsearch\Transport-&gt;performRequest('HEAD', '/_template/411_...', Array, NULL, Array) #3 /var/www/411/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection-&gt;Elasticsearch\Connections\{closure}(Array) #4 /var/www/411/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise-&gt;then(Object(Closure), NULL, NULL) #5 /var/ in <b>/var/www/411/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php</b> on line <b>51</b><br />`
![image](https://user-images.githubusercontent.com/19161126/30274790-8cf2ec38-971c-11e7-9885-6ebe64a96699.png)

**Comment by v-sukt** [comment]
hi, as mentioned in comment on readme, it assumes a cluster setup with hostname 'es' so in if its container with name elasticsearch you can link it to 411 container with 
`docker run -p 8080:80 --link elasticsearch:es kaiz/411`
or make entry in /etc/hosts file es x.x.x.x where x.x.x.x is the IP of your cluster and copy the file in the container with `docker cp /etc/hosts container_name:/etc/hosts`
other alternative to test it directly is to update the IP of elasticsearch cluster in running container

> Editing networking config files
> 
> Starting with Docker v.1.2.0, you can now edit /etc/hosts, /etc/hostname and /etc/resolve.conf in a running container. This is useful if you need to install bind or other services that might override one of those files.
> 
> Note, however, that changes to these files will not be saved by docker commit, nor will they be saved during docker run. That means they won't be saved in the image, nor will they persist when a container is restarted; they will only "stick" in a running container.
> 
> source: https://docs.docker.com/articles/networking/#editing-networking-config-files
