### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by lucasjkr** [kiwiz/411-docker#6]
The change in Branches at 411 has caused this container to stop building; just FYI

**Comment by lucasjkr** [comment]
I forked your repository, to have it use separate containers for web, cron, and MySQL.

It's still quite sloppy (files duplicated between the 411 containers), and the cron.php and worker.php generate errors.

Wondering if you'd want it back when I'm done, or do you want the Docker image to continue using SQLite?

**Comment by kiwiz** [comment]
Thanks for the notif. I'd like to keep a standalone docker container, though I'd be happy to maintain a more complicated `docker-compose.yml` set up as well. If you eventually open a PR, I can set up a separate build.

**Comment by kiwiz** [comment]
Moving all docker config into the main repo (etsy/411).
